version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: shl-assessment-recommender
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    env_file:
      - .env
    environment:
      - LOG_LEVEL=DEBUG
    restart: always
